spring.datasource.url=jdbc:mysql://138.197.64.182:1218/librosmario
spring.datasource.username=root
spring.datasource.password=nat74tam


spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql=true

#Agrego esto por el error cuando agregue soporte para DSL
#Description:

#The bean 'pageableResolver', defined in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/data/web/config/HateoasAwareSpringDataWebConfiguration.class] and overriding is disabled.

#Action:

#Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true


#spring.main.allow-bean-definition-overriding=true


## App Properties
app.jwtSecret= JWTSuperSecretKey
app.jwtExpirationInMs = 604800000


endpoints.beans.sensitive=false

endpoints.info.enabled=true
endpoints.info.sensitive=false

info.app.name=Pedidos Backend

#para actuator
management.endpoints.web.exposure.include=*

#para que srping batch cree las tablas solo
spring.batch.initialize-schema=ALWAYS
spring.batch.job.enabled=false

pedidos.luongo.path=/aplicaciones/pedidos/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


