spring.datasource.url=jdbc:mysql://localhost:1218/librosmario?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=nat74tam

pedidos.luongo.path=./data/

logging.config=classpath:log4j2-local.xml

sentry.environment=${SENTRY_ENVIRONMENT:local}
