spring.datasource.url=jdbc:mysql://localhost:3306/librosmario
spring.datasource.username=librosmario
spring.datasource.password=dracula

#Agrego esto por el error cuando agregue soporte para DSL
#Description:

#The bean 'pageableResolver', defined in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/data/web/config/HateoasAwareSpringDataWebConfiguration.class] and overriding is disabled.

#Action:

#Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true


#spring.main.allow-bean-definition-overriding=true